### PR TITLE
boards: norik: Add support for Norik Octopus SoM & IO-Board

### PR DESCRIPTION
**Pull request by FPlohl**
Add support for Norik Octopus SoM & IO-Board based on nRF9160 SiP.

### CODE REVIEW

**Review by pfiser — APPROVED** [review]

**Review by andrejpicej — COMMENTED** [review]
LGTM, except in Copyrigt is "Norik systems d.o.o." right or should ti be "Norik Systems d.o.o."?

**Comment by FPlohl** [comment]
Changed Norik systems d.o.o. to Norik Systems as requested.

**Comment by pfiser** [comment]
@FPlohl you still have one rename left in "boards/norik/octopus_som/board.cmake" to be consistent.

**Comment by FPlohl** [comment]
@pfiser fixed remaining inconsistencies. Clear to open PR to main branch?

**Comment by pfiser** [comment]
yes, @FPlohl go ahead and open PR on upstream zephyr repo. Fingers crossed :)

**Pull request merged**
